{% set name = "pytool" %}
{% set version = "3.16.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytool-{{ version }}.tar.gz
  sha256: 5ce9613900e59b62419f9ba566cd88fff4afc87612fd467ca8d0f0dac96253a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - simplejson >=3.2.0
    - six

test:
  imports:
    - pytool
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/shakefu/pytool
  summary: A Collection of Python Tools
  doc_url: https://pytool.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - ruben-arts
